# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GachaData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'GachaData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LanguageStringData_pb2 as LanguageStringData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fGachaData.proto\x12\x08gf2gacha\x1a\x18LanguageStringData.proto\"\xcd\x01\n\rGachaDataUnit\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04type\x18\x04 \x01(\x03\x12\x11\n\tstartTime\x18\x07 \x01(\x03\x12\x0f\n\x07\x65ndTime\x18\x08 \x01(\x03\x12*\n\x04name\x18\t \x01(\x0b\x32\x1c.gf2gacha.LanguageStringData\x12\x12\n\nrateDesGun\x18\x16 \x01(\t\x12\x15\n\rrateDesWeapon\x18\x17 \x01(\t\x12\x11\n\tgunUpItem\x18\x1b \x01(\t\x12\x14\n\x0cweaponUpItem\x18\x1d \x01(\t\"3\n\tGachaData\x12&\n\x05Units\x18\x01 \x03(\x0b\x32\x17.gf2gacha.GachaDataUnitb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GachaData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GACHADATAUNIT']._serialized_start=56
  _globals['_GACHADATAUNIT']._serialized_end=261
  _globals['_GACHADATA']._serialized_start=263
  _globals['_GACHADATA']._serialized_end=314
# @@protoc_insertion_point(module_scope)
