# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ItemData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ItemData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LanguageStringData_pb2 as LanguageStringData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eItemData.proto\x12\x08gf2gacha\x1a\x18LanguageStringData.proto\"p\n\x0cItemDataUnit\x12\n\n\x02id\x18\x01 \x01(\x03\x12*\n\x04name\x18\x02 \x01(\x0b\x32\x1c.gf2gacha.LanguageStringData\x12\x0c\n\x04type\x18\x05 \x01(\x03\x12\x0c\n\x04icon\x18\x07 \x01(\t\x12\x0c\n\x04rank\x18\x08 \x01(\x03\"1\n\x08ItemData\x12%\n\x05Units\x18\x01 \x03(\x0b\x32\x16.gf2gacha.ItemDataUnitb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ItemData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMDATAUNIT']._serialized_start=54
  _globals['_ITEMDATAUNIT']._serialized_end=166
  _globals['_ITEMDATA']._serialized_start=168
  _globals['_ITEMDATA']._serialized_end=217
# @@protoc_insertion_point(module_scope)
