# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: LangPackageTableCnData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'LangPackageTableCnData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LanguageStringData_pb2 as LanguageStringData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cLangPackageTableCnData.proto\x12\x08gf2gacha\x1a\x18LanguageStringData.proto\"9\n\x1aLangPackageTableCnDataUnit\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"M\n\x16LangPackageTableCnData\x12\x33\n\x05Units\x18\x01 \x03(\x0b\x32$.gf2gacha.LangPackageTableCnDataUnitb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LangPackageTableCnData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LANGPACKAGETABLECNDATAUNIT']._serialized_start=68
  _globals['_LANGPACKAGETABLECNDATAUNIT']._serialized_end=125
  _globals['_LANGPACKAGETABLECNDATA']._serialized_start=127
  _globals['_LANGPACKAGETABLECNDATA']._serialized_end=204
# @@protoc_insertion_point(module_scope)
